# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lycée privé hors contrat Saint-John Perse - Paris 18
email: sjp018@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Enseignement secondaire privé hors contrat à Paris depuis 1982
  Paris 18 - 14, rue Cavallotti - 01 43 87 73 10
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ecoles-sjp.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: St_JohnPerse
facebook_username: etablissements saint john perse

menus:
  main:
  - title: Approche
    identifier: approche
  - title: Filière
    identifier: filiere
  - title: Scolarité
    identifier: scolarite
  - title: Prépa Sciences Po
    identifier: prepasciencespo
    url: http://www.prepasciencespo-sjp.fr
  - title: Contact
    identifier: contact
    url: /contact

  approche:
  - title: Nos valeurs
    url: /approche/nos-valeurs
    identifier: valeurs
  - title: Suivi individualisé et étude dirigée
    url: /approche/suivi-individualise-et-etude-dirigee
    identifier: suivi
  - title: Cadre de vie ouvert sur le monde
    url: /approche/cadre-de-vie-ouvert-sur-le-monde
    identifier: cadre
  - title: Ateliers d'arts plastiques, de cinéma ou de théatre
    url: /approche/ateliers-d-arts
    identifier: ateliers
  - title: Horaires aménagés Arts ou Sports
    url: /approche/horaires-amenages
    identifier: horaires

  filiere:
  - title: Seconde générale
    url: /filieres/seconde-generale
    identifier: seconde
  - title: Littéraire Arts (L)
    url: /filieres/litteraire-arts-plastiques-ou-cinema
    identifier: litteraire-arts
  - title: Littéraire Langues (L)
    url: /filieres/litteraire-langues-l
    identifier: litteraire-langues
  - title: Scientifique (S)
    url: /filieres/scientifique-s
    identifier: scientifique
  - title: Éco et social (ES)
    url: /filieres/eco-et-social-es
    identifier: eco-et-social
  - title: Management (STMG)
    url: /filieres/management-stmg
    identifier: smtg

  scolarite:
  - title: Tarifs et conditions d'inscription
    url: /scolarite/tarifs-et-conditions-d-inscription
    identifier: tarifs
  - title: Documents utiles
    url: /scolarite/documents-utiles
    identifier: documents-utiles
  - title: Cahier de texte
    url: http://ecolesjp.free.fr/
    identifier: cahier-de-texte
  - title: Stage de rentrée
    url: /scolarite/stage-de-rentree
    identifier: stage



# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
