# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: L'Ecole Saint-John Perse, un lycée privé à Paris
subtitle: Prépas ESA, ingénieurs, douanes, gendarmerie, GPX, CRPE
email: sjp018@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Enseignement secondaire privé hors contrat à Paris depuis 1982
  Paris 18ème - 14, rue Cavallotti - 01 43 87 73 10
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ecoles-sjp.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: St_JohnPerse
facebook_username: etablissements saint john perse
google_analytics: UA-124493340-1
lang: fr_FR

menus:
  main:
  - title: Accueil
    url: /
    identifier: accueil
  - title: Notre Ecole
    identifier: ecole
    url: /approche/index
  - title: Nos classes
    identifier: filiere
    url: /filieres/index
  - title: La scolarité
    identifier: scolarite
    url: /scolarite/index
  - title: Nos Prépas
    identifier: prepa
    url: /prepa/index
  - title: Nous contacter
    identifier: contact
    url: /contact

  ecole:
  - title: Nos valeurs
    url: /approche/nos-valeurs
    identifier: valeurs
  - title: Suivi individualisé et étude dirigée
    url: /approche/suivi-individualise-et-etude-dirigee
    identifier: suivi
  - title: Cadre de vie ouvert sur le monde
    url: /approche/cadre-de-vie-ouvert-sur-le-monde
    identifier: cadre
  - title: Les ateliers
    url: /approche/ateliers-d-arts
    identifier: ateliers

  filiere:
  - title: Seconde générale
    url: /filieres/seconde-generale
    identifier: seconde
  - title: Première générale
    url: /filieres/premiere-generale
    identifier: premiere
  - title: Première Management et Gestion (STMG)
    url: /filieres/premiere-management-et-gestion
    identifier: premiere-stmg
  - title: Terminale Littéraire Langues ou Cinéma (BAC L)
    url: /filieres/litteraire-arts-plastiques-ou-cinema
    identifier: litteraire-arts
  - title: Terminale Scientifique (BAC S)
    url: /filieres/scientifique-s
    identifier: scientifique
  - title: Terminale Éco et social (BAC ES)
    url: /filieres/eco-et-social-es
    identifier: eco-et-social
  - title: Terminale Management et Gestion (BAC STMG)
    url: /filieres/management-stmg
    identifier: smtg
    
  scolarite:
  - title: Tarifs et bourses
    url: /scolarite/tarifs-et-conditions-d-inscription
    identifier: tarifs
  - title: Documents à télécharger
    url: /scolarite/documents-utiles
    identifier: documents-utiles
  - title: Cahier de texte en ligne
    url: http://ecolesjp.free.fr/
    identifier: cahier-de-texte
  - title: Stages 
    url: /scolarite/stage-de-rentree
    identifier: stage

  prepa:
  - title: Prépa Concours CRPE
    url: /prepa/prepa-crpe
    identifier: crpe
  - title: Prépa Concours ESA
    url: /prepa/prepa-concours-esa-ecole-de-sante-des-armees
    identifier: esa
  - title: Prépa Concours Ecoles d'ingénieurs
    url: /prepa/prepa-aux-concours-des-ecoles-d-ingenieur-post-bac
    identifier: ingenieur
  - title: Prépa Concours Gendarmerie
    url: /prepa/prepa-au-concours-de-l-ecole-de-gendarmerie
    identifier: concoursgendarmerie
  - title: Prépa Concours Communs
    url: /prepa/prepa-concours-communs
    identifier: concourscommun
  - title: Prépa Sciences Po
    url: http://www.prepasciencespo-sjp.fr/
    identifier: sciencespo
  
# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
